//! The serialised shape of every command, pinned.
//!
//! Murmur is in a better position here than a binary format would be: RON
//! names its variants and fields rather than numbering them, so inserting a
//! variant into the middle of [`Command`] does *not* renumber the others, and
//! a recorded mission keeps replaying. The failure this file catches is the
//! other one — a *rename*. Rename a variant or a field and every previously
//! recorded value stops parsing, or worse, parses into a different shape.
//!
//! It matters more than it looks, because [`world_fingerprint`] is a hash of
//! `ron::to_string(world)`. The RON text is not a debugging convenience, it is
//! the thing being hashed, so every serde attribute on every type reachable
//! from `World` is part of the save format. `golden.rs` notices when that
//! moves; this file says what moved.
//!
//! Sample values are arbitrary but fixed. What is pinned is the shape, not the
//! payload.
//!
//! To re-bless after a *deliberate* format change, run with
//! `MURMUR_BLESS_COMMAND_SHAPE=1`.

use std::fmt::Write as _;

use murmur_core::actions::{Cheat, Command};
use murmur_core::geom::{Dir4, Pos};
use murmur_core::map::DoorId;
use murmur_core::world::{ActorId, FurnitureId};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/command_shape.txt"
);

fn samples() -> Vec<(&'static str, Command)> {
    vec![
        ("Move", Command::Move(Dir4::North)),
        ("Wait", Command::Wait),
        ("ToggleCrouch", Command::ToggleCrouch),
        ("OpenDoor", Command::OpenDoor(DoorId(3))),
        ("CloseDoor", Command::CloseDoor(DoorId(4))),
        ("Garrote", Command::Garrote(ActorId(1))),
        ("Shoot", Command::Shoot(ActorId(2))),
        ("Pickpocket", Command::Pickpocket(ActorId(5))),
        (
            "TakeDisguiseFromBody",
            Command::TakeDisguiseFromBody(ActorId(6)),
        ),
        (
            "TakeDisguiseFromWardrobe",
            Command::TakeDisguiseFromWardrobe(FurnitureId(7)),
        ),
        ("CarryBody", Command::CarryBody(ActorId(8))),
        ("DropBody-none", Command::DropBody(None)),
        ("DropBody-dir", Command::DropBody(Some(Dir4::East))),
        ("HideBody", Command::HideBody(FurnitureId(9))),
        ("DrawOrHolster", Command::DrawOrHolster),
        ("PickLock", Command::PickLock(DoorId(10))),
        (
            "ThrowNoisemaker",
            Command::ThrowNoisemaker(Pos::new(1, 12, 13)),
        ),
        ("Interact", Command::Interact(FurnitureId(14))),
        ("Cheat", Command::Cheat(Cheat::BlindNpcs)),
    ]
}

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# project-murmur command serialised shape. Generated by command_shape.rs;\n\
         # do not hand-edit. A diff here changes what recorded missions parse as.\n",
    );

    for direction in Dir4::ALL {
        let text = ron::to_string(&direction).expect("direction serialises");
        let _ = writeln!(out, "Dir4::{direction:?} = {text}");
    }
    for cheat in Cheat::ALL {
        let text = ron::to_string(&cheat).expect("cheat serialises");
        let _ = writeln!(out, "Cheat::{cheat:?} = {text}");
    }
    for (name, command) in samples() {
        let text = ron::to_string(&command).expect("command serialises");
        let _ = writeln!(out, "Command::{name} = {text}");
    }
    out
}

#[test]
fn command_shape_is_pinned() {
    let rendered = render();

    if std::env::var("MURMUR_BLESS_COMMAND_SHAPE").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset MURMUR_BLESS_COMMAND_SHAPE and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with MURMUR_BLESS_COMMAND_SHAPE=1 to create it")
    });

    for (want, got) in expected.lines().zip(rendered.lines()) {
        assert_eq!(
            want, got,
            "the serialised command shape moved.\n\
             Recorded missions parse against the old names, and every type \
             reachable from World feeds world_fingerprint."
        );
    }
    assert_eq!(
        expected.lines().count(),
        rendered.lines().count(),
        "the set of serialised commands changed size: a variant was added or removed"
    );
}

/// Sanity: the pinned text must decode back to what it encodes, or the fixture
/// is pinning a broken serialiser just as happily.
#[test]
fn pinned_commands_round_trip() {
    for (name, command) in samples() {
        let text = ron::to_string(&command).expect("serialises");
        let back: Command = ron::from_str(&text).expect("deserialises");
        assert_eq!(back, command, "{name} did not survive a round trip");
    }
}
