//! Golden missions: exact values, pinned to a file.
//!
//! The other suites assert *properties* — this rule fires, that one does not.
//! Properties survive a refactor that changes everything consistently, which
//! is precisely the refactor a shared engine layer is. This file asserts
//! values instead: for a fixed set of seeds, the autoplayer's command log and
//! the resulting [`world_fingerprint`] must come out byte-identical to what
//! they were when the fixture was blessed.
//!
//! That covers the whole pipeline in one number. A fingerprint moves if
//! generation draws differently, if the planner certifies a different layout,
//! if an action resolves differently, if a serde field is reordered, or if the
//! RNG changes. It cannot tell you *which*, which is what
//! `tests/rng_trace.rs` is for — that one isolates the generator, so a red
//! fingerprint with a green trace means the sim moved and the RNG did not.
//!
//! Every accepted command is also replayed through [`replay`] and the
//! fingerprints compared, so the record this file pins is a record that
//! actually reproduces.
//!
//! To re-bless after a *deliberate* change, run with `MURMUR_BLESS_GOLDEN=1`.
//! An extraction must never need that: a diff here means saved missions no
//! longer replay.

use std::fmt::Write as _;

use murmur_core::autoplay::autoplay;
use murmur_core::contract::MissionConfig;
use murmur_core::data::GameData;
use murmur_core::generator::generate;
use murmur_core::replay::{MissionRecord, replay, world_fingerprint};
use murmur_core::turn::TurnDriver;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/golden.txt");

/// Seeds per venue. Small because every one is a full mission driven to an
/// ending in a debug build; the fixture's job is to be sensitive, not broad,
/// and the wide sweep lives in `murmur-cli -- corpus`.
const SEEDS: u64 = 4;

fn render(data: &GameData) -> String {
    let mut out = String::new();
    out.push_str(
        "# project-murmur golden missions. Generated by golden.rs; do not hand-edit.\n\
         # venue seed outcome turns commands fingerprint\n",
    );

    for venue in &data.venues {
        for seed in 0..SEEDS {
            let config = MissionConfig::new(seed, venue.id.clone());
            let world = match generate(data, &config) {
                Ok(world) => world,
                Err(error) => {
                    let _ = writeln!(out, "{} {seed} GENERATION-FAILED {error:?}", venue.id);
                    continue;
                }
            };
            let generated = world_fingerprint(&world);
            let mut driver = TurnDriver::new(world, data);
            let report = autoplay(data, &mut driver);
            let played = world_fingerprint(driver.world());

            // The record must reproduce the run it describes. This is the
            // property the whole save format rests on, checked here against
            // real logs rather than hand-built ones.
            let record = MissionRecord {
                config: config.clone(),
                commands: report.commands.clone(),
            };
            let replayed = replay(data, &record).expect("the recorded mission replays");
            assert_eq!(
                world_fingerprint(&replayed),
                played,
                "{} seed {seed}: replaying the command log produced a different world",
                venue.id
            );

            let _ = writeln!(
                out,
                "{} {seed} {} {} {} {generated:016x} {played:016x}",
                venue.id,
                report
                    .outcome
                    .as_ref()
                    .map(|outcome| format!("{outcome:?}"))
                    .unwrap_or_else(|| "unfinished".to_owned()),
                report.turns,
                report.commands.len(),
            );
        }
    }
    out
}

#[test]
fn golden_missions_are_pinned() {
    let data = GameData::embedded().expect("embedded content");
    let rendered = render(&data);

    if std::env::var("MURMUR_BLESS_GOLDEN").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset MURMUR_BLESS_GOLDEN and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with MURMUR_BLESS_GOLDEN=1 to create it")
    });

    let expected_lines: Vec<&str> = expected.lines().collect();
    let actual_lines: Vec<&str> = rendered.lines().collect();
    for (index, (want, got)) in expected_lines.iter().zip(&actual_lines).enumerate() {
        assert_eq!(
            want,
            got,
            "golden mission {} of {FIXTURE} changed.\n\
             A fingerprint moved, so a saved mission no longer replays. If \
             `rng_trace` is still green the generator is intact and the change \
             is in the simulation or in what gets serialised.",
            index + 1
        );
    }
    assert_eq!(
        expected_lines.len(),
        actual_lines.len(),
        "the set of golden missions changed size"
    );
}
