//! A raw trace of the mission PRNG, pinned to a file.
//!
//! `pcg32_matches_reference_vector` already holds six words against the
//! canonical pcg32-demo output, which is enough to catch a rewritten
//! generator. This file exists for a different failure: when a mission
//! fingerprint moves during a refactor, the question is whether the
//! *generator* changed or whether the same generator was merely consulted in a
//! different order. Six words cannot tell those apart. A long trace can — if
//! this file still matches and the fingerprints do not, the draw order changed
//! and the RNG did not.
//!
//! Both named streams are traced. `Stream::Generation` and
//! `Stream::Resolution` are separate PCG streams so that rejecting a player
//! command cannot consume layout randomness; a change that collapsed them
//! would leave `next_u32` intact and still invalidate every replay, and only a
//! two-stream trace catches it.
//!
//! `shuffle` gets its own section because it is the helper whose *draw count*
//! is easiest to change by accident: Fisher-Yates draws once per element, so
//! an off-by-one in the loop bound shifts every subsequent draw in the
//! generation stream without changing a single value this file would otherwise
//! see.
//!
//! To re-bless after a *deliberate* change, run with
//! `MURMUR_BLESS_RNG_TRACE=1`. Nothing in an extraction should ever need that;
//! a diff here is the finding.

use std::fmt::Write as _;

use murmur_core::rng::{Pcg32, Stream, split_mix_64};

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/rng_trace.txt");

/// Words per line. Eight keeps a divergence to a short line so the diff points
/// at a draw index rather than a paragraph.
const PER_LINE: usize = 8;

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# project-murmur Pcg32 trace. Generated by rng_trace.rs; do not hand-edit.\n\
         # A diff in this file means the generator moved. See the module docs.\n",
    );

    for seed in [0u64, 1, 42, 0xDEAD_BEEF] {
        for (label, stream) in [
            ("Generation", Stream::Generation),
            ("Resolution", Stream::Resolution),
        ] {
            let mut rng = Pcg32::for_stream(seed, stream);
            let _ = writeln!(out, "\n[next_u32 seed={seed} stream={label} count=512]");
            emit(&mut out, (0..512).map(|_| rng.next_u32()));
        }
    }

    // The canonical reference construction, traced far past the six words the
    // unit test pins, so a divergence that only shows up after the warm-up is
    // still caught here.
    let mut rng = Pcg32::new(42, 54);
    let _ = writeln!(out, "\n[next_u32 canonical seed=42 selector=54 count=512]");
    emit(&mut out, (0..512).map(|_| rng.next_u32()));

    // Bounds chosen to exercise the rejection loop rather than dodge it: 5 and
    // 100 are the shapes the generator actually draws, 3 is small enough that
    // rejection fires often, and 0x8000_0001 is just above half of u32::MAX,
    // the worst case where nearly half of all draws are rejected.
    for bound in [3u32, 5, 100, 1000, 0x8000_0001] {
        let mut rng = Pcg32::for_stream(0, Stream::Generation);
        let _ = writeln!(out, "\n[below seed=0 bound={bound} count=2048]");
        emit(&mut out, (0..2048).map(|_| rng.below(bound)));
    }

    let mut rng = Pcg32::for_stream(0, Stream::Generation);
    let _ = writeln!(out, "\n[range_inclusive seed=0 lo=2 hi=7 count=1024]");
    emit(&mut out, (0..1024).map(|_| rng.range_inclusive(2, 7)));

    // `chance` takes a numerator and denominator rather than a percent, so it
    // is traced at a ratio that is not a round percentage: a refactor to
    // percent-based odds would still pass a 50/100 trace.
    let mut rng = Pcg32::for_stream(0, Stream::Resolution);
    let _ = writeln!(out, "\n[chance seed=0 num=3 den=7 count=1024]");
    emit(&mut out, (0..1024).map(|_| u32::from(rng.chance(3, 7))));

    // Shuffle, traced as the resulting permutation at several lengths. This is
    // what pins the draw count, not just the draw values.
    let mut rng = Pcg32::for_stream(0, Stream::Generation);
    let _ = writeln!(out, "\n[shuffle seed=0 lengths=1..=48]");
    for len in 1..=48u32 {
        let mut items: Vec<u32> = (0..len).collect();
        rng.shuffle(&mut items);
        emit(&mut out, items.into_iter());
    }

    // `take` mutates the vector it draws from, so its draw sequence depends on
    // the shrinking length. Traced as the order in which a fixed pool empties.
    let mut rng = Pcg32::for_stream(0, Stream::Generation);
    let _ = writeln!(out, "\n[take seed=0 pool=64]");
    let mut pool: Vec<u32> = (0..64).collect();
    let drained: Vec<u32> = (0..64).map(|_| rng.take(&mut pool)).collect();
    emit(&mut out, drained.into_iter());

    // Seed succession: "play again" reproducibility depends on this chain.
    let _ = writeln!(out, "\n[split_mix_64 chain from=0 count=256]");
    let mut seed = 0u64;
    let chain: Vec<u64> = (0..256)
        .map(|_| {
            seed = split_mix_64(seed);
            seed
        })
        .collect();
    emit_u64(&mut out, chain.into_iter());

    out
}

fn emit(out: &mut String, values: impl Iterator<Item = u32>) {
    let mut column = 0;
    for value in values {
        let _ = write!(out, "{value:08x}");
        column += 1;
        if column == PER_LINE {
            out.push('\n');
            column = 0;
        } else {
            out.push(' ');
        }
    }
    if column != 0 {
        out.push('\n');
    }
}

fn emit_u64(out: &mut String, values: impl Iterator<Item = u64>) {
    let mut column = 0;
    for value in values {
        let _ = write!(out, "{value:016x}");
        column += 1;
        if column == 4 {
            out.push('\n');
            column = 0;
        } else {
            out.push(' ');
        }
    }
    if column != 0 {
        out.push('\n');
    }
}

#[test]
fn rng_trace_is_pinned() {
    let rendered = render();

    if std::env::var("MURMUR_BLESS_RNG_TRACE").is_ok() {
        std::fs::create_dir_all(
            std::path::Path::new(FIXTURE)
                .parent()
                .expect("fixtures dir"),
        )
        .expect("create fixtures dir");
        std::fs::write(FIXTURE, &rendered).expect("write fixture");
        panic!("re-blessed {FIXTURE}; unset MURMUR_BLESS_RNG_TRACE and re-run to confirm");
    }

    let expected = std::fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("{FIXTURE}: {error}\nrun once with MURMUR_BLESS_RNG_TRACE=1 to create it")
    });

    // Compare line by line so the failure names the draw index, not the file.
    // `lines()` normalises line endings: the fixture is text and git may check
    // it out with CRLF on Windows, which is not a determinism finding.
    let expected_lines: Vec<&str> = expected.lines().collect();
    let actual_lines: Vec<&str> = rendered.lines().collect();

    let mut section = "<header>";
    for (index, (want, got)) in expected_lines.iter().zip(&actual_lines).enumerate() {
        if want.starts_with('[') {
            section = want;
        }
        assert_eq!(
            want,
            got,
            "the PRNG trace diverged at line {} of {FIXTURE}, in section {section}.\n\
             The generator changed. If that was deliberate it is a replay-format \
             change, not a refactor: every recorded mission replays against the \
             old sequence.",
            index + 1
        );
    }
    assert_eq!(
        expected_lines.len(),
        actual_lines.len(),
        "the PRNG trace changed length: the set of draws being traced moved"
    );
}
